name: 소환사 전적 업데이트 - 그랜드마스터

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["소환사 전적 업데이트 - 챌린저"]
    types: 
      - completed

jobs:
  update-summoner-records:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      RIOT_API_KR_ROOT: ${{ secrets.RIOT_API_KR_ROOT }}
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
      SUMMONER_ID_FILE_PATH: "summoner_ids.txt"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fetch grandmaster summoner IDs
        run: python .github/scripts/fetch_summoner_id.py --tier grandmaster

      - name: Update summoner records
        run: python .github/scripts/update_summoner_records.py