name: 정적 데이터 업데이트
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0'  # KST 매주 월요일 00시 (UTC 15:00)

env:
  TZ: Asia/Seoul

jobs:
  update-static-data:
    runs-on: ubuntu-latest
    env:
      SERVER_URL: ${{ secrets.SERVER_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run update_static_data.py
        run: python src/update_static_data.py
